image: debian/stable
sources:
  - https://github.com/MarkPash/schnitzel-gallery.git
packages:
  - curl
tasks:
  - rust: |
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly --profile minimal -y
  - build: |
      source $HOME/.cargo/env
      cd schnitzel-gallery
      cargo build
